---
- name: Stat parent of dest
  stat:
    path: "{{ cacerts_certificate[cacerts_group_key]['paths']|c2platform.core.cacerts_dirname }}"
  register: dest_parent

- block: # skip if parent does not exist
    - name: Copy private key
      copy:
        src: "/tmp/{{ cert_key.filename|basename }}"
        dest: "{{ pth['key'] }}"
        owner: "{{ pth['owner']|default(omit) }}"
        group: "{{ pth['group']|default(omit) }}"
      with_items: "{{ cacerts_certificate[cacerts_group_key]['paths'] }}"
      loop_control:
        loop_var: pth
      when: pth['key'] is defined

    - name: Copy certificate
      copy:
        src: "/tmp/{{ cert_crt.filename|basename }}"
        dest: "{{ pth['crt'] }}"
        owner: "{{ pth['owner']|default(omit) }}"
        group: "{{ pth['group']|default(omit) }}"
      with_items: "{{ cacerts_certificate[cacerts_group_key]['paths'] }}"
      loop_control:
        loop_var: pth
      notify: "{{ cacerts_certificate[cacerts_group_key]['notify']|default(omit) }}"
      when: pth['crt'] is defined

    - name: Copy pem
      copy:
        src: "/tmp/{{ ca_domain_cert[cert_deploy]['common_name'] }}.pem"
        dest: "{{ pth['pem'] }}"
        owner: "{{ pth['owner']|default(omit) }}"
        group: "{{ pth['group']|default(omit) }}"
      with_items: "{{ cacerts_certificate[cacerts_group_key]['paths'] }}"
      loop_control:
        loop_var: pth
      notify: "{{ cacerts_certificate[cacerts_group_key]['notify']|default(omit) }}"
      when: pth['pem'] is defined

    - name: Copy p12
      copy:
        src: "/tmp/{{ ca_domain_cert[cert_deploy]['common_name'] }}.p12"
        dest: "{{ pth['p12'] }}"
        owner: "{{ pth['owner']|default(omit) }}"
        group: "{{ pth['group']|default(omit) }}"
      with_items: "{{ cacerts_certificate[cacerts_group_key]['paths'] }}"
      loop_control:
        loop_var: pth
      notify: "{{ cacerts_certificate[cacerts_group_key]['notify']|default(omit) }}"
      when: pth['p12'] is defined
  when: dest_parent.stat.exists