---
- name: Block sessions
  postgresql_query:
    db: postgres
    login_host: "{{ vars[ lcm_role_upgrade + '_database_host' ] }}"
    login_user: "{{ vars[ lcm_role_upgrade + '_database_admin_username' ] }}"
    login_password: "{{ vars[ lcm_role_upgrade + '_database_admin_password' ] }}"
    port: "{{ vars[ lcm_role_upgrade + '_database_port' ] }}"
    query: update pg_database SET datallowconn = 'false' WHERE datname = %s
    positional_args:
      - "{{ terminate_database }}"

- name: Terminate sessions
  postgresql_query:
    db: postgres
    login_host: "{{ vars[ lcm_role_upgrade + '_database_host' ] }}"
    login_user: "{{ vars[ lcm_role_upgrade + '_database_admin_username' ] }}"
    login_password: "{{ vars[ lcm_role_upgrade + '_database_admin_password' ] }}"
    port: "{{ vars[ lcm_role_upgrade + '_database_port' ] }}"
    query: select pg_terminate_backend(pid) from pg_stat_activity where datname = %s
    positional_args:
      - "{{ terminate_database }}"
