---
- name: deploy lib
  ansible.builtin.get_url:
    url: "{{ lib.url }}"
    dest: "{{ tomcat_directory }}//{{ instance.name }}/lib/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  when:
    - lib.url is defined
  notify:
    - restart tomcat instance
