---
- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Group
  group:
    name: "{{ tomcat_group }}"
    state: present

- name: User
  user:
    name: "{{ tomcat_user }}"
    state: present
    group: "{{ tomcat_group }}"
    createhome: yes
    system: yes

- name: Home directory
  file:
    path: "{{ tomcat_home_version }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: "0755"

- name: Create home link
  file:
    src: "{{ tomcat_home_version }}"
    dest: "{{ tomcat_home_link }}"
    state: link

- name: Stat bin dir # e.g. /opt/tomcat/tomcat-9.0.40/bin
  stat:
    path: "{{ tomcat_home_version }}/bin"
  register: bin_folder

- include: install.yml
  when: not bin_folder.stat.exists

- include: configure.yml
- include: git_repos.yml
  when: tomcat_git_config is defined
- include: configure_manager.yml
- include: cert.yml

- name: Deploy Tomcat apps
  include: apps.yml
  loop: "{{ tomcat_apps }}"
  loop_control:
    loop_var: app
  when:
    - tomcat_apps is defined
  no_log: no

- include: service.yml
- include: lib.yml
#- include: jmx.yml

- name: PAM limits # /etc/security/limits.conf
  pam_limits:
    domain: "{{ tomcat_user }}"
    limit_type: "{{ item['limit_type'] }}"
    limit_item: nofile
    value: "{{ item['value'] }}"
  with_items: "{{ tomcat_pam_limits_nofile }}"
  when: tomcat_pam_limits_nofile is defined
